#!/bin/bash
#
# link - Link scripts into parent directory
#
# Assuming you have checked out in plugings/WorldEdit/craftscripts/kators-worldedit-craftscripts
#

DIR=$(basename $PWD)

if [ "X$DIR" == "X.git" ]; then
  cd ..
  DIR=$(basename $PWD)
fi

SCRIPTS=$(echo *.js)

echo "Linking scripts to $DIR"
cd ..
for i in $SCRIPTS
do
  rm -f $i > /dev/null 2>&1
  ln -vs $DIR/$i .
done

exit 0
